# Players => Layout Mapping
first_card: &first_card
  top: 180px
  left: 115px
first_player: &first_player
  top: 310px
  left: 15px
top_card: &top_card
  top: 10px
  left: 115px
top_player: &top_player
  top: -120px
  left: 15px
left_card: &left_card
  top: 95px
  left: 10px
left_player: &left_player
  top: 80px
  left: -280px
right_card: &right_card
  top: 95px
  left: 220px
right_player: &right_player
  top: 80px
  left: 310px
top_left_card: &top_left_card
  <<: *left_card
  top: 10px
top_right_card: &top_right_card
  <<: *right_card
  top: 10px
top_left_player: &top_left_player
  <<: *left_player
  top: -10px
top_right_player: &top_right_player
  <<: *right_player
  top: -10px
bottom_left_card: &bottom_left_card
  <<: *left_card
  top: 140px
bottom_right_card: &bottom_right_card
  <<: *right_card
  top: 140px
bottom_left_player: &bottom_left_player
  <<: *left_player
  top: 140px
bottom_right_player: &bottom_right_player
  <<: *right_player
  top: 140px

0:
  none: here

1:
  top_margin: 40px
  cards:
    - <<: *first_card
  players:
    - <<: *first_player
2: 
  top_margin: 100px
  cards:
    - <<: *first_card
    - <<: *top_card
  players:
    - <<: *first_player
    - <<: *top_player
3:
  top_margin: 40px
  cards:
    - <<: *first_card
    - <<: *top_left_card
    - <<: *top_right_card
  players:
    - <<: *first_player
    - <<: *top_left_player
    - <<: *top_right_player
4:
  top_margin: 100px
  cards:
    - <<: *first_card
    - <<: *left_card
    - <<: *top_card
    - <<: *right_card
  players:
    - <<: *first_player
    - <<: *left_player
    - <<: *top_player
    - <<: *right_player
5:
  top_margin: 40px
  cards:
    - <<: *first_card
    - <<: *bottom_left_card
    - <<: *top_left_card
      left: 40px
    - <<: *top_right_card
      left: 190px
    - <<: *bottom_right_card
  players:
    - <<: *first_player
    - <<: *bottom_left_player
    - <<: *top_left_player
      top: -50px
    - <<: *top_right_player
      top: -50px
    - <<: *bottom_right_player
6:
  top_margin: 100px
  cards:
    - <<: *first_card
    - <<: *bottom_left_card
    - <<: *top_left_card
      left: 20px
    - <<: *top_card
      top: 5px
    - <<: *top_right_card
      left: 210px
    - <<: *bottom_right_card
  players:
    - <<: *first_player
    - <<: *bottom_left_player
    - <<: *top_left_player
      top: -50px
    - <<: *top_player
    - <<: *top_right_player
      top: -50px
    - <<: *bottom_right_player
7:
  top_margin: 100px
  cards:
    - <<: *first_card
    - <<: *bottom_left_card
      top: 160px
      left: 20px
    - <<: *top_left_card
      left: 10px
      top: 30px
    - <<: *top_card
      top: 5px
      left: 80px
    - <<: *top_card
      top: 5px
      left: 150px
    - <<: *top_right_card
      left: 220px
      top: 30px
    - <<: *bottom_right_card
      top: 160px
      left: 210px

  players:
    - <<: *first_player
    - <<: *bottom_left_player
    - <<: *top_left_player
      top: -50px
    - <<: *top_player
      left: -80px
    - <<: *top_player
      left: 110px
    - <<: *top_right_player
      top: -50px
    - <<: *bottom_right_player

8:
  top_margin: 100px
  cards:
    - <<: *first_card
    - <<: *bottom_left_card
      top: 170px
      left: 30px
    - <<: *left_card
    - <<: *top_card
      top: 25px
      left: 45px
    - <<: *top_card
    - <<: *top_card
      top: 25px
      left: 185px
    - <<: *right_card
    - <<: *bottom_right_card
      top: 170px
      left: 200px

  players:
    - <<: *first_player
    - <<: *bottom_left_player
      top: 170px
    - <<: *top_left_player
      top: 50px
    - <<: *top_player
      left: -200px
    - <<: *top_player
    - <<: *top_player
      left: 230px
    - <<: *top_right_player
      top: 50px
    - <<: *bottom_right_player
      top: 170px
9:
  top_margin: 100px
  cards:
    - <<: *first_card
    - <<: *bottom_left_card
      top: 170px
      left: 30px
    - <<: *left_card
    - <<: *top_card
      top: 25px
      left: 25px
    - <<: *top_card
      left: 80px
    - <<: *top_card
      left: 150px
    - <<: *top_card
      top: 25px
      left: 205px
    - <<: *right_card
    - <<: *bottom_right_card
      top: 170px
      left: 200px

  players:
    - <<: *first_player
    - <<: *bottom_left_player
      top: 170px
    - <<: *left_player
      top: 80px
    - <<: *left_player
      top: -10px
    - <<: *top_player
      left: -95px
    - <<: *top_player
      left: 125px
    - <<: *right_player
      top: -10px
    - <<: *right_player
      top: 80px
    - <<: *bottom_right_player
      top: 170px

10:
  top_margin: 100px
  cards:
    - <<: *first_card
    - <<: *bottom_left_card
      top: 170px
      left: 30px
    - <<: *left_card
      top: 115px
    - <<: *left_card
      top: 30px
      left: 20px
    - <<: *top_card
      left: 60px
      top: 15px
    - <<: *top_card
    - <<: *top_card
      left: 170px
      top: 15px
    - <<: *right_card
      top: 30px
      left: 210px
    - <<: *right_card
      top: 115px
    - <<: *bottom_right_card
      top: 170px
      left: 200px

  players:
    - <<: *first_player
    - <<: *bottom_left_player
      top: 180px
    - <<: *left_player
      top: 90px
    - <<: *left_player
      top: 0px
    - <<: *top_player
      left: -175px
    - <<: *top_player
    - <<: *top_player
      left: 205px
    - <<: *right_player
      top: 0px
    - <<: *right_player
      top: 90px
    - <<: *bottom_right_player
      top: 180px
